image: moodlehq/moodle-workplace-plugin-ci:8.0-ci4.1.5

services:
- postgres:13
#- mysql:5.7.26
- name: selenium/standalone-chrome:3
  alias: selenium-standalone-chrome

variables:
  MOODLE_REPO_WORKPLACE: git@git.in.moodle.com:workplace/workplacedev.git
  MOODLE_BRANCH_WORKPLACE402R: WORKPLACE_ROLLING_402
  MOODLE_BRANCH_WORKPLACE402S: WORKPLACE_402
  MOODLE_REPO_LMS: git@git.in.moodle.com:moodle/moodle.git
  MOODLE_BRANCH_LMS402: MOODLE_402_STABLE
  MOODLE_BRANCH_LMS403: MOODLE_403_STABLE
  MOODLE_BEHAT_WDHOST: "http://selenium-standalone-chrome:4444/wd/hub"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: "trust"
  MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  DB: "pgsql"
#  DB: "mysqli"
  MUSTACHE_IGNORE_NAMES: 'mobile*.mustache'

before_script:
- export MOODLE_REPO=$MOODLE_REPO_WORKPLACE
- export MOODLE_BRANCH=$MOODLE_BRANCH_WORKPLACE402R
- . prepare-workplace $cibot_sshkey
- cd $CI_PROJECT_DIR/..
- moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_wp.git
- moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_tenant.git
- moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-theme_workplace.git
- moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_organisation.git
- moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_reportbuilder.git
- moodle-plugin-ci install --db-host="$DB_HOST" --no-init -vvv
- php -S ${IPADDRESS}:8000 -t $CI_PROJECT_DIR/../moodle > /dev/null 2>&1 &
- cd moodle

jobtest:
  script:
  - php admin/tool/phpunit/cli/util.php --install
  - php admin/tool/phpunit/cli/util.php --buildconfig
  - php admin/tool/phpunit/cli/util.php --buildcomponentconfigs
  - php admin/tool/behat/cli/init.php --add-core-features-to-theme
  - . check-start
  - . check no_workplace_licenses
  - . check this_plugin_is_part_of "the block_rbreport plugin for Moodle - http://moodle.org/" --nowplicensecomment
  - . check version_number
  - . check language_file_sorting
  - . check behat_workplace_tag
  - . check moodle-plugin-ci phplint
  #- . check moodle-plugin-ci phpcpd
  #- . check moodle-plugin-ci phpmd
  - . check moodle-plugin-ci codechecker --max-warnings 0
  - . check moodle-plugin-ci phpdoc
  - . check moodle-plugin-ci validate
  - . check moodle-plugin-ci savepoints
  - . check moodle-plugin-ci mustache
  - . check moodle-plugin-ci grunt --max-lint-warnings 0
  - . check vendor/bin/phpunit --fail-on-risky --disallow-test-output --testsuite tool_dataprivacy_testsuite --filter metadata_registry_test
  - . check vendor/bin/phpunit --fail-on-risky --disallow-test-output --testsuite core_external_testsuite --filter test_all_external_info
  - . check vendor/bin/phpunit --fail-on-risky --disallow-test-output --testsuite core_privacy_testsuite --filter provider_test
  - . check vendor/bin/phpunit --fail-on-risky --disallow-test-output --testsuite tool_tenant_testsuite --filter block_rbreport
  - . check moodle-plugin-ci phpunit --coverage-text --fail-on-warning
  - . check moodle-plugin-ci behat --suite workplace --profile chrome
  - . check-finish
  except:
  - tags

.scriptshorttest: &scriptshorttest
  script:
    - . prepare-workplace $cibot_sshkey
    - cd $CI_PROJECT_DIR/..
    - moodle-plugin-ci install --db-host="$DB_HOST" --no-init -vvv
    - cd moodle
    - php admin/tool/phpunit/cli/init.php
    - php admin/tool/phpunit/cli/util.php --buildcomponentconfigs
    - php -S ${IPADDRESS}:8000 -t $CI_PROJECT_DIR/../moodle > /dev/null 2>&1 &
    - php admin/tool/behat/cli/init.php --add-core-features-to-theme --parallel=3 --optimize-runs=@block_rbreport
    - . check-start
    - . check moodle-plugin-ci phpunit --coverage-text --fail-on-warning
    - . check moodle-plugin-ci behat --suite default --profile chrome
    - . check-finish

wp402s:
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_WORKPLACE
    - export MOODLE_BRANCH=$MOODLE_BRANCH_WORKPLACE402S
  <<: *scriptshorttest
  except:
    - master
    - tags
    - /^WORKPLACE_\d+$/

lms402:
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_LMS
    - export MOODLE_BRANCH=$MOODLE_BRANCH_LMS402
  <<: *scriptshorttest
  except:
    - master
    - tags

lms403:
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_LMS
    - export MOODLE_BRANCH=$MOODLE_BRANCH_LMS403
  <<: *scriptshorttest
  except:
    - master
    - tags
